### ISSUE TITLE
Copyright holder and license

### ISSUE THREAD

**Issue by marcelometal** [globocom/docker-local-telemetry#1]
Hi,
Could you please add LICENSE file and put the copyright holder and license inside each file?

This way there is no chance of someone stumbling across a piece of code without being exposed to the license.

Thanks!

**Comment by meyer1994** [comment]
Is it really necessary? This is just a demo. If it is, which one does the organisation uses normally? MIT?

**Comment by meyer1994** [comment]
Closing because I've added a MIT license file. If you feel that is still needed to add the license to the top of all files, I'll gladly reopen this issue
